version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/top_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root

