version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      docker: 20
    commands:
      - echo "Installing dependencies"
      - apt-get update && apt-get install -y git

  pre_build:
    commands:
      - echo "Cloning the GitHub repository"
      - git clone https://github.com/kartikeyametikoti/repo_for_pushing_to_dockerhub.git app
      - cd app
      - echo "Repository cloned successfully"

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t flask-app .
      - echo "Docker image built successfully"

  post_build:
    commands:
      - echo "Build phase completed!"

artifacts:
  files:
    - "**/*"

