name: Deploy Flask App with Docker

on:
  push:
    branches:
      - main  # Trigger on  pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check  out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub (or another registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t my-flask-app:latest .

    # Step 4: Push Docker  image to Docker Hub
    - name: Push Docker image
      run: |
        docker tag my-flask-app:latest kartikeya1112/python_project:latest
        docker push kartikeya1112/python_project:latest

    # Step 5: Deploy  container to EC2
    - name: Deploy to EC2
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$SSH_KEY" > kartikkey.pem
        sudo chmod 600 kartikkey.pem
        ssh -o StrictHostKeyChecking=no -i kartikkey.pem $EC2_USER@$EC2_HOST << EOF
          sudo yum update
          sudo yum install docker -y
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo docker ps | awk 'NR>1 {print $1}' |sudo xargs docker stop && sudo xargs docker rm
          sudo docker pull kartikeya1112/python_project:latest
          sudo docker stop flask-app || true
          sudo docker rm flask-app || true
          sudo docker run -d --name flask-app -p 80:5000 kartikeya1112/python_project:latest
        EOF

